# Self-Assessment
I thoroughly understood the content of the third lecture and completed all assigned exercises.
The concepts were clear and well-structured, which allowed me to apply the coding norms confidently.
I now have a fair understanding of how to write scripts for the markdown cells and have taken less help from the AI tools, unlike the first assignment.

## Problems Faced While Completing the Exercises
- **Content Generation and Structure:** Utilized ChatGPT and Gemini to assist in creating the professional markdown files with clear formatting and structure.

# Assignment Number 6.6 Data Science: Duplicate Word Removal
**Exercise Description** (Duplicate Word Removal) 
- Write a function that receives a list of words, then determines and returns a sorted list of the unique words.
- Treat uppercase and lowercase the same—for example, if the list contains *apple* and *Apple*, the list you return should contain *apple* once.
- The caller should display the unique words in alphabetical order with one word per line. Test your function by calling it several times with different sentences. Remember to break each sentence into a list of words before passing it to the function.

**LabAssist:** 
- The techniques used here are data-wrangling operations.


In [88]:
def return_sorted_unique_list(sentence):
    """ This function returns a sorted list of the unique words from a given sentence."""
    words_lower = [words.lower() for words in sentence]
    unique_words = set(words_lower) ##unique words in the given list
    return(sorted(unique_words))

In [89]:
input_sentence = 'My favorite subject subject Is Is Python'
print(f'The input sentence is: {input_sentence}')
print('------ Output below----------')
##Split the sentence into individual words and pass it as a list
split_sentence = input_sentence.split()
sorted_unique  = return_sorted_unique_list(split_sentence)
for words in sorted_unique:
    print(words)

The input sentence is: My favorite subject subject Is Is Python
------ Output below----------
favorite
is
my
python
subject


In [90]:
input_sentence = 'Dodgers GAME game was full FULL OF ENTERTAINMENT entertainment'
print(f'The input sentence is: {input_sentence}')
print('------ Output below----------')

##Split the sentence into individual words and pass it as a list
split_sentence = input_sentence.split()
sorted_unique  = return_sorted_unique_list(split_sentence)
for words in sorted_unique:
    print(words)

The input sentence is: Dodgers GAME game was full FULL OF ENTERTAINMENT entertainment
------ Output below----------
dodgers
entertainment
full
game
of
was


## Code Explanation ##

**Explanation of the defined function**
- The function **return_sorted_unique_list** takes the string split into its words.
- Converts all the words in the sentence to lowercase
- Extracts a unique set of words i.e. it removes the duplicates word in the sentence
       - The **set** function hlps to removes the duplicate
- Returns the sorted list of words in the sentence
       - The **sorted** commands helps top sort the list passed as an argument

**Main Code**
- The input sentence whose words have to be sorted and printed is passed to the defined function **return_sorted_unique_list**
- The list obtained is then iterated to print out the words in lexicographical order

# Assignment Number 6.9 Dictionary Manipulations

**Exercise Description**
Using the following dictionary, which maps country names to Internet top-level domains (TLDs):
    - tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}
perform the following tasks and display the results:

- Check whether the dictionary contains the key 'Canada'.
- Check whether the dictionary contains the key 'France'.
- Iterate through the key–value pairs and display them in two-column format.
- Add the key–value pair 'Sweden' and 'sw' (which is incorrect).
- Update the value for the key 'Sweden' to 'se'.
- Use a dictionary comprehension to reverse the keys and values.
- With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.

**6.9(a)Check whether the dictionary contains the key 'Canada'**

In [91]:
##Create a dictionary first
country_domain_map = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'} 

In [92]:
'Canada' in country_domain_map

True

### The code checks whether or not the value 'Canada' is present as a key ot not in dictionary

**6.9(b)Check whether the dictionary contains the key 'France'**

In [93]:
'France' in country_domain_map

False

### The code checks whether or not the value 'France' is present as a key ot not in dictionary

**6.9(c)Iterate through the key–value pairs and display them in two-column format**

In [94]:
for country, domain in country_domain_map.items():
    print(f'{country:<20}{domain}')

Canada              ca
United States       us
Mexico              mx


- The iteration on key value pair is done using the 'for' loop
- The **.items()** function retrieves the key value pair

**6.9(d)Add the key–value pair 'Sweden' and 'sw' (which is incorrect)**

In [95]:
country_domain_map['Sweden'] = 'sw'

In [96]:
country_domain_map

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

- The new key value pair is added to the existing directory through assignment operation

**6.9(e)Update the value for the key 'Sweden' to 'se'**

In [97]:
country_domain_map['Sweden'] = 'se'

In [98]:
country_domain_map

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

- The new key value pair is updated for 'Sweden' through assignment operation

**6.9(f)Use a dictionary comprehension to reverse the keys and values**

In [99]:
reversed_country_domain_map = {value: key for key, value in country_domain_map.items()}

In [100]:
reversed_country_domain_map

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

- The key value pair is reversed using the comprehension.
- The old 'key' is mapped to the 'value'
- The old 'value' is mapped to the 'key'

**6.9(g)With the result of above part use a dictionary comprehension to convert the country names to all uppercase letters**

In [101]:
new_country_domain_map = {key:value.upper() for key, value in reversed_country_domain_map.items()}

In [102]:
new_country_domain_map

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

- The individual value of the each key-value pair is converted to UPPER CASE using the **.upper()** function
- The iteration is done using a dictionary comprehension method to achieve this result

# Assignment Number 7.2 Broadcasting

## Problem Statement:
- Use arange to create a 2-by-2 array containing the numbers 0–3.
- Use broadcasting to perform each of the following operations on the original array:
    - a) Cube every element of the array.
    - b) Add 7 to every element of the array.
    - c) Multiply every element of the array by 2.

In [127]:
import numpy as np

In [128]:
two_dim_array = np.arange(0,4).reshape(2,2)
two_dim_array

array([[0, 1],
       [2, 3]])

- The **import function** is used to import the numerical python library which is then used to create an array of size 2*2
- The **arange function* generates numbers for the array from 0 upto 3
- The **reshape function** then translates the four numbers(0,1,2,3) into a 2D array

**7.2(a)Cube every element of the array**

In [129]:
two_dim_array = two_dim_array ** 3
two_dim_array

array([[ 0,  1],
       [ 8, 27]])

**The above function cubes each value**

**7.2(b)Add 7 to every element of the array**

In [130]:
two_dim_array += 7
two_dim_array

array([[ 7,  8],
       [15, 34]])

**The above function adds 7 to each value of array**

**7.2(c)Multiply every element of the array by 2**

In [131]:
two_dim_array = two_dim_array * 2
two_dim_array

array([[14, 16],
       [30, 68]])

# Assignment Number 7.9 Data Science: Indexing and Slicing arrays

## Problem Statement:
Create an array containing the values 1–15,reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each
of the following operations:
- a) Select row 2.
- b) Select column 5.
- c) Select rows 0 and 1.
- d) Select columns 2–4.
- e) Select the element that is in row 1 and column 4.
- f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

## LabAssist notes:Model your code
- **Part (b)** has a typo in the original exercise description it should say, “Select column 4.” not “Select column 5.

In [137]:
two_dimensional_Array = np.arange(1,16).reshape(3,5)
two_dimensional_Array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

- The above command **np.arange** generates numbers from 1,15
- The command **.reshape** generates a 3 by 5 matrix/2-D array containing those 15 numbers

**7.9(a)Select row 2**

In [138]:
second_row = two_dimensional_Array[1]
second_row

array([ 6,  7,  8,  9, 10])

- The array index position starts from 0. hence the 1st position is the second index and thus the command **two_dimensional_Array[1]** generates only the second row

**7.9(b)Select column 4**

In [153]:
column_four = two_dimensional_Array[0:,4]
column_four

array([ 5, 10, 15])

- **0:** selects rows starting from row 0 all the way to the last row.
- **4**  selects column index 4

**7.9(c)Select rows 0 and 1**

In [154]:
display_zero_one = two_dimensional_Array[0:2,]
display_zero_one

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Breakdown of Code**

- 0:2 → select rows 0 and 1 (row index 2 is excluded) , → since nothing is specified after the comma, it selects all columns
- So this returns rows 0 and 1, including all their columns, as a 2D array.

**7.9(d)Select columns 2–4**

In [162]:
display_col_two_four = two_dimensional_Array[:,2:]
display_col_two_four

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

**Breakdown of code**
- : → select all rows
- 2: → select columns starting from index 2 (third column) to the last column
So this returns all rows, but only columns 2, 3, 4, … depending on the array shape.

**7.9(e)Select the element that is in row 1 and column 4.**

In [165]:
two_dimensional_Array[1][4]

np.int64(10)

**This is accessing a specific element in a 2D NumPy array (or a list of lists) using two separate indexing operations**
- two_dimensional_Array[1] → selects row 1 (the second row, since indexing starts at 0)
- [4] → selects column 4 (the fifth element) from that row
So it returns the element at row 1, column 4.

**7.9(f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.**

In [171]:
two_dimensional_Array[np.ix_([1,2],[0,2,4])]

array([[ 6,  8, 10],
       [11, 13, 15]])

**np.ix_([1,2],[0,2,4])** creates broadcastable index arrays so that every row selected is combined with every column selected.